### ISSUE TITLE
`checked-changed` fired when bound data loads into the component

### ISSUE THREAD

**Issue by colinjlacy** [PredixDev/px-toggle#7]
## Expected behavior and actual behavior:

I have an event listener set up for the `checked-changed` event, to do some things programmatically when a user toggles this component.  Unfortunately, the `checked-changed` event seems to fire when the DOM loads, and bound data sets the internal value of the component to `true`.  I'd expect there to be an event triggered specifically for when a user interacts with the component, so that I can track that instead. 

Currently I'm working around this by tracking the `click` event instead.  So it's not a pressing issue, just something to consider.

Note that this is:
- in an Angular 4.4.6 app
- using the 2.1.1 version of this component
- in Chrome 64.0.3282.140 
- on macOS 10.12.6.

## Steps to reproduce the problem:

Apply an event listener to the `checked-changed` event.  Mine looks like this:
```
<px-toggle size="small" 
    [checked]="row.active" 
    (checked-changed)="toggleTenantStatus(row.guid, row.title)">
</px-toggle>
```
```
private toggleTenantStatus(id: string, title: string): void {
    // anything, really...
}
```
make sure `const row = {active: true}`

**You'll see the event handler fired twice**

...which isn't the end of the world.  It would just be nice to be able to subscribe to a different event instead that indicates that it was triggered by a user, and comes packaged with the boolean value of the checkbox.

**Comment by randyaskin** [comment]
Yeah, we don't really have control over the `checked-changed` event, since it's automatically generated by notifying properties in Polymer. One of the changes from Polymer v1 to v2 was that observers and notifiers get triggered when properties go from undefined to their default value, as you noticed.

In v2.2.0, I added a `px-toggle-checked-changed` event on discrete user action, where `detail` will contain the new value (true/false). Google still has an open bug in their API analyzer for events, so unfortunately it won't show up on the API page quite yet, but hopefully that helps.

**Comment by colinjlacy** [comment]
It absolutely does.  Thank you sir!
